# Generated by Django 5.1.1 on 2024-09-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pizza",
            name="name",
        ),
    ]
