# Generated by Django 5.1.1 on 2024-09-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_core", "0002_remove_pizza_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crust",
            old_name="price_modifier",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("making", "Making"),
                    ("baking", "Baking"),
                    ("on_the_way", "On the way"),
                    ("ready_for_pickup", "Ready for pickup"),
                    ("complete", "Complete"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
